'use client'

import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Mulish } from "next/font/google";
import { SessionProvider } from "next-auth/react";
import Toast from "./components/Toast";
import { ShowToastContext } from "@/context/ShowToastContext";
import { useState } from "react";
import { ParentFolderIdContext } from "@/context/ParentFolderIdContext";
import Storage from "./components/Storage/Storage";



const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

 const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [showToastMsg, setShowToastMsg] = useState<string | null | undefined>();
  const [parentFolderId, setParentFolderId] = useState<string | null | undefined>();


  return (
    <html lang="en">
      <body
       className={mulish.variable}
      >
        <SessionProvider>
          <ParentFolderIdContext.Provider value={{parentFolderId: parentFolderId, setParentFolderId}}>
          <ShowToastContext.Provider value={{ showToastMsg: (msg: string) => setShowToastMsg(msg), setShowToastMsg }}>
        <div className="flex">
          <Navbar />
          <div className="grid grid-cols-1 md:grid-cols-3 w-full">
            <main className="col-span-2 bg-sky-50">
              
              {children}
            </main>
            <div className="bg-white sticky p-5 order-first md:order-last m-5">
              <Storage/>
            </div>
          </div>
   
        </div>
     
        
      
        {showToastMsg && <Toast msg={showToastMsg}/>}
        </ShowToastContext.Provider>
        </ParentFolderIdContext.Provider>
        </SessionProvider>
      </body>
    </html>
  );
}
